### ISSUE TITLE
Error when running the script on 1.19.2

### ISSUE THREAD

**Issue by Kotemorte** [Egobooster/ComputerCraft-GeoMiner#1]
![Scree33nshot_38](https://github.com/Egobooster/ComputerCraft-GeoMiner/assets/48981351/c3116cb9-4ca1-4d71-ac9a-c60d98e2f581)

mods: CC: Tweaked, Ender Storage, Advanced Peripherals (1.19.2)

**Comment by Egobooster** [comment]
Hi, first up thanks for using my program, I think that's really cool and I'm happy to help!

I've updated the repo a while ago and I forgot to update the pastebin links. I've now updated them, so I'd recommend to download geomine.lua and startup.lua again.

Could you tell me what command you used to start the program? It seems that the ```facing``` variable is not set.

**Comment by Kotemorte** [comment]
![image](https://github.com/Egobooster/ComputerCraft-GeoMiner/assets/48981351/f2d3de62-ee16-4378-90d4-e4c3ae28ef4b)
Hi! Yes I updated the script and ran it, initially for some reason it gives an error after scanning.
It says something like there is not enough fuel, I put several stacks of coal but it still says there is not enough fuel, until I turned on the function fuel_enderchest and put coal there.
And as you can see in the screenshot, I gave the turtle a task to mine iron, but as you can see it ignored the iron and went on about its business, moving around imitating normal work ;3
[geomine.log](https://github.com/Egobooster/ComputerCraft-GeoMiner/files/12616757/geomine.log)
![image](https://github.com/Egobooster/ComputerCraft-GeoMiner/assets/48981351/942120ef-82bd-4589-a4f6-9f81e91bc596)
![image](https://github.com/Egobooster/ComputerCraft-GeoMiner/assets/48981351/6aa292d9-5e94-462f-a831-d5b8d1b2e3aa)

**Comment by Egobooster** [comment]
Hmm, thats interesting.
>It says something like there is not enough fuel, I put several stacks of coal but it still says there is not enough fuel, until I turned on the function fuel_enderchest and put coal there.

The scanning cost can become quite large as it scales exponentially with the radius. When you enable the enderchest the Turtle just assumes it will get infinite fuel. I assume you exceeded the fuel requirements for the scan. I also think there is a maximum radius of about ~16 given by the GeoScanner from AdvancedPeripherals.

Here you can see the Error you probably encountered:
```
    -- scan
    cost = gs.cost(radius)
    if cost > turtle.getFuelLevel() then
      if fuel_enderchest then
        dorefuel()
      else
        log("not enough fuel!")
        error("not enough fuel for scanning!")
      end
    end
```

>And as you can see in the screenshot, I gave the turtle a task to mine iron, but as you can see it ignored the iron and went on about its business, moving around imitating normal work ;3

Haha, I think the turtle isn't trying to avoid work but that the Iron Ore is likely at the edge of the scan. ;)

For example it would only mine the ores that are in the blue circle:

![example](https://github.com/Egobooster/ComputerCraft-GeoMiner/assets/26220053/664dfa94-db73-491d-88d6-6b4449bd3645)

**Comment by Kotemorte** [comment]
It sounds interesting, but I set the default scan radius to 8

**Comment by Egobooster** [comment]
I see what might be the problem, did you tell the turtle to refuel?

Try running ```refuel all``` before running the program. If that fixes it I will write a patch so it tries that before failing.

**Comment by Kotemorte** [comment]
Bro! Yes after entering the command refuel all it consumed a stack of coal and gave a message how much energy is in it, after that I started it to work and everything was without errors ( By the way, the last turtle from the last post filled with everything you can fill your inventory and ender chest and extracted only 22 pieces of iron ) 

I think it would be possible to implement config to record there 'items' that should be discarded every certain cycle of time, but we can not add anything to config because every cobble in the farm will be useful, even if you have a huge cobble farm made with the Create mod ;) 
**Waiting for an update**

**Comment by Egobooster** [comment]
That's great to hear! I will write a patch so that the turtle tries to refuel itself when launching without an enderchest and then close this issue.

> I think it would be possible to implement config to record there 'items' that should be discarded every certain cycle of time

Interesting idea, I currently always filtered on the enderchests end but it should not be very hard to implement that.
