### ISSUE TITLE
label:enhancement Finding your turtle if it's lost will be easier. 

### ISSUE THREAD

**Issue by Kotemorte** [Egobooster/ComputerCraft-GeoMiner#2]
We need to get the turtle to record its coordinates.
Instead of just providing data on what level Y it is at now, we can provide all X Y Z before the start.
'geomine n 8 X Y Z _ore'.

Create a file XYZ.txt before start and write the coordinates we specified here 'geomine n 8 X Y Z _ore'.
After all this turtle goes into mining mode. And all we need to do is in XYZ.txt to write in each new line of the coordinates of how the turtle moves, but it will count from zero coordinates.
And if the turtle realizes that there's no fuel and it's about to give an error about lack of fuel, before that we ask it to solve the problem.

Let's assume that the initial global coordinates (where the turtle's movement started) are (144, 63, 91) and the current coordinates of the operator are (X, Y, Z). To compute the global coordinates of the operator, we must add its current coordinates to the initial global coordinates. However, to account for possible negative coordinates, we must also add its memorized displacements relative to the zero coordinates.

Thus, the calculation of the global coordinates will look as follows:

Global X = Initial X + X of the operator
Global Y = Initial Y + Y of the operator
Global Z = Initial Z + Z of the operator

Where:

Initial X, Initial Y and Initial Z are the initial global coordinates (144, 63, 91).
Operator X, Operator Y and Operator Z are the current coordinates of the operator that the operator has memorized relative to the zero coordinates.
Example:

If the operator's current coordinates (X, Y, Z) = (10, -5, 20), then:

Global X = 144 + 10 = 154
Global Y = 63 - 5 = 58
Global Z = 91 + 20 = 111

Thus, the operator is on global coordinates (154, 58, 111).

And at the end we save the current global coordinates of the turtle to a file. I hope you will understand me...

**Comment by Egobooster** [comment]
Yes I think I understand what you mean. The Turtle does currently do exactly what you are describing, it just doesn't use global coordinates but the relative position to the original starting position. 

By using the relative position it can calculate how much fuel it requires to get home and is also able to resume the program after a server restart etc.

The relative position is saved in the file ```gps.data```

I don't think it's necessary to record the global position. If you have trouble finding the turtle, you can calculate it's position using the ```gps.data``` file. Just do this:

Global X = Starting X + Relative X
Global Y = Starting Y + Relative Y
Global Z = Starting Z + Relative Z

Here is the function that records the coordinates (separated using ```;```):
```
function savepos()
  gps = fs.open("gps.data","w")
  gps.write(x .. ";")
  gps.write(y .. ";")
  gps.write(z .. ";")
  gps.write(facing .. "")
  gps.close()
end  
```
